name: flutter_environments_plus
description: "A Flutter package for detecting the current platform, with added features like desktop/mobile and more web detection options."
version: 1.0.2
repository: https://github.com/Calebh101/flutter_environments

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0